spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: xiongyilun
    password: 1
    driver-class-name: oracle.jdbc.driver.OracleDriver
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

