spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: xiongyilun
    password: 1
    driver-class-name: oracle.jdbc.driver.OracleDriver
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  redis:
    host: 127.0.0.1
    port: 6379

mybatis:
  configuration:
    #配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
    map-underscore-to-camel-case: true
